# Generated by Django 4.2 on 2023-05-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0003_appuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="section_end",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="section_start",
            new_name="start",
        ),
    ]
