# Generated by Django 4.2 on 2023-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0004_rename_section_end_section_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ww", "compiling with warnings"),
                    ("co", "compiling without warnings"),
                    ("nc", "not compiling"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("pro", "procedure"),
                    ("com", "comment"),
                    ("dir", "compiler directive"),
                    ("var", "variable declaration"),
                    ("asm", "asembler code"),
                ],
                default="pro",
                max_length=3,
            ),
        ),
    ]
