# Generated by Django 4.2 on 2023-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0005_section_section_status_section_section_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="section_status",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="section",
            name="section_type",
        ),
        migrations.AddField(
            model_name="section",
            name="type",
            field=models.CharField(
                choices=[
                    ("pro", "procedure"),
                    ("com", "comment"),
                    ("dir", "compiler directive"),
                    ("var", "variable declaration"),
                    ("asm", "asembler code"),
                ],
                default="com",
                max_length=3,
            ),
        ),
    ]
