# Generated by Django 4.2 on 2023-05-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_editor", "0006_rename_section_status_section_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="type",
            field=models.CharField(
                choices=[
                    ("pro", "procedure"),
                    ("com", "comment"),
                    ("dir", "compiler directive"),
                    ("var", "variable declaration"),
                    ("asm", "asembler code"),
                ],
                max_length=3,
            ),
        ),
    ]
